
CREATE DATABASE LongaVida;
USE LongaVida;


CREATE TABLE PLANO (
    Numero CHAR(2) NOT NULL,      
    Descricao CHAR(30),           
    Valor DECIMAL(10,2),          
    PRIMARY KEY (Numero)
);


CREATE TABLE ASSOCIADO (
    Plano CHAR(2) NOT NULL,       
    Nome CHAR(40) NOT NULL,       
    Endereco CHAR(35),             
    Cidade CHAR(20),              
    Estado CHAR(2),               
    CEP CHAR(9),                  
    PRIMARY KEY (Nome),
    FOREIGN KEY (Plano) REFERENCES PLANO (Numero) 
        ON DELETE CASCADE 
        ON UPDATE CASCADE
);


INSERT INTO PLANO (Numero, Descricao, Valor) VALUES 
    ('B1', 'BASICO 1', 100.00),
    ('B2', 'BASICO 2', 120.00),
    ('B3', 'BASICO 3', 140.00),
    ('E1', 'EXECUTIVO 1', 300.00),
    ('E2', 'EXECUTIVO 2', 350.00),
    ('E3', 'EXECUTIVO 3', 400.00),
    ('M1', 'MASTER 1', 500.00),
    ('M2', 'MASTER 2', 550.00),
    ('M3', 'MASTER 3', 600.00);


INSERT INTO ASSOCIADO (Plano, Nome, Endereco, Cidade, Estado, CEP) VALUES
    ('B1', 'JOSE DA SILVA', 'RUA 1', 'SANTO ANDRE', 'SP', '09000-000'),
    ('E2', 'MARIA SANTOS', 'RUA 2', 'DIADEMA', 'SP', '09999-999'),
    ('M3', 'PEDRO JOSE DE OLIVEIRA', 'RUA 3', 'SÃO PAULO', 'SP', '01000-010');

SELECT ASSOCIADO.Nome, ASSOCIADO.Plano, PLANO.Descricao
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero;


SELECT COUNT(*) AS Total_B1
FROM ASSOCIADO
WHERE Plano = 'B1';


SELECT ASSOCIADO.Nome, ASSOCIADO.Plano, PLANO.Valor
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero;


SELECT Nome
FROM ASSOCIADO
WHERE Cidade IN ('COTIA', 'DIADEMA');


SELECT ASSOCIADO.Nome, ASSOCIADO.Plano, PLANO.Valor
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
WHERE ASSOCIADO.Cidade = 'BARUERI' AND ASSOCIADO.Plano = 'M1';


SELECT ASSOCIADO.Nome, ASSOCIADO.Plano, PLANO.Valor
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
WHERE ASSOCIADO.Cidade = 'SÃO PAULO';


SELECT *
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
WHERE ASSOCIADO.Nome LIKE '%SILVA%';


UPDATE PLANO
SET Valor = CASE
    WHEN Descricao LIKE 'BASICO%' THEN Valor * 1.10
    WHEN Descricao LIKE 'EXECUTIVO%' THEN Valor * 1.05
    WHEN Descricao LIKE 'MASTER%' THEN Valor * 1.03
    ELSE Valor
END;


UPDATE ASSOCIADO
SET Plano = 'E3'
WHERE Nome = 'PEDRO JOSE DE OLIVEIRA';


SELECT COUNT(*) AS Total_E3
FROM ASSOCIADO
WHERE Plano = 'E3';


SELECT ASSOCIADO.Nome, PLANO.Valor
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
WHERE ASSOCIADO.Plano IN ('B1', 'E1', 'M1');


SELECT Nome
FROM ASSOCIADO
WHERE Plano LIKE 'E%';


SELECT Nome
FROM ASSOCIADO
WHERE Plano LIKE 'B%' OR Plano LIKE 'M%';


DELETE FROM ASSOCIADO
WHERE Cidade = 'SANTO ANDRE';


SELECT ASSOCIADO.Nome, ASSOCIADO.Plano, PLANO.Valor
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
WHERE ASSOCIADO.Cidade = 'SÃO PAULO' AND ASSOCIADO.Plano IN ('M2', 'M3')
ORDER BY ASSOCIADO.Nome;


SELECT *
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
ORDER BY PLANO.Descricao;


SELECT ASSOCIADO.Nome, ASSOCIADO.Plano, PLANO.Descricao
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
ORDER BY PLANO.Descricao ASC, ASSOCIADO.Nome DESC;


SELECT Nome
FROM ASSOCIADO
WHERE Plano NOT LIKE 'M%';


SELECT ASSOCIADO.Nome, PLANO.Descricao
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
ORDER BY ASSOCIADO.Nome ASC;


SELECT *
FROM PLANO
WHERE Valor BETWEEN 300 AND 500;


SELECT ASSOCIADO.Nome, ASSOCIADO.Plano, PLANO.Descricao, PLANO.Valor
FROM ASSOCIADO
JOIN PLANO ON ASSOCIADO.Plano = PLANO.Numero
WHERE ASSOCIADO.Nome LIKE '%AMARAL%';


SELECT Nome
FROM ASSOCIADO
WHERE Cidade = 'DIADEMA';


UPDATE PLANO
SET Valor = Valor * 1.06
WHERE Descricao LIKE 'MASTER%';


SELECT Nome
FROM ASSOCIADO
WHERE CEP LIKE '09%';
